CREATE TABLE IF NOT EXISTS public.addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep VARCHAR(8) NOT NULL,
    state VARCHAR(2) NOT NULL,
    city VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    complement VARCHAR(255),
    number BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.animal_shelters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    responsible_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(11) NOT NULL,
    address_id BIGINT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_animal_shelters_address
        FOREIGN KEY (address_id)
        REFERENCES public.addresses(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.species (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specie_name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    specie BIGINT NOT NULL,
    age BIGINT NULL,
    animal_shelter_id BIGINT NULL,
    adopted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_pets_species
        FOREIGN KEY (specie)
        REFERENCES public.species(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pets_animal_shelters
        FOREIGN KEY (animal_shelter_id)
        REFERENCES public.animal_shelters(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.user_adopters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(11) NOT NULL,
    address_id BIGINT NULL,
    pet_id BIGINT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_user_adopters_address
        FOREIGN KEY (address_id)
        REFERENCES public.addresses(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_adopters_pet
        FOREIGN KEY (pet_id)
        REFERENCES public.pets(id)
        ON DELETE CASCADE
);