from .animal_shelter_repository_spy import AnimalShelterRepositorySpy
from .pet_repository_spy import PetRepositorySpy
from .address_repository_spy import AddressRepositorySpy
from .specie_repository_spy import SpecieRepositorySpy
